# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - n8n-deploy-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fc1ec64f0b324fb89345f71adfac77be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_af92dc4c10324e94b021b7a19e5956b3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fc1ec64f0b324fb89345f71adfac77be }}/john894/n8n-azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'n8n-deploy-azure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e87bfa94ce47477e842992bf75031fab }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fc1ec64f0b324fb89345f71adfac77be }}/john894/n8n-azure:${{ github.sha }}'